version: "3"
services:
  azure-storage:
    image: azure-storage
    build:
      context: ../azure-storage
      dockerfile: Dockerfile-prod
    container_name: video-storage
    ports:
      - 4001:80
    restart: "no"
  video-streaming:
    image: video-streaming
    build:
      context: ../video-streaming
      dockerfile: Dockerfile-prod
    container_name: video-streaming
    ports:
      - 4002:80
    restart: "no"
  history:
    image: video-history
    build:
      context: ../video-history
      dockerfile: Dockerfile-dev
    container_name: video-history
    volumes:
      - /tmp/video-history/npm-cache:/root/.npm:z
      - ../video-history/src:/usr/src/app/src:z
    ports:
      - 4002:80
    restart: no
