version: "3"
services:
  azure-storage:
    image: azure-storage
    build:
      context: ../azure-storage
      dockerfile: Dockerfile-prod
    container_name: video-storage
    ports:
      - 4001:80
    restart: "no"
  video-streaming:
    image: video-streaming
    build:
      context: ../video-streaming
      dockerfile: Dockerfile-prod
    container_name: video-streaming
    ports:
      - 4002:80
    restart: "no"
  history:
    image: video-history
    build:
      context: ../video-history
      dockerfile: Dockerfile-prod
    container_name: video-history
    ports:
      - 4003:80
    restart: "no"
  rabbit:
    image: rabbitmq:3.8.1
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    restart: "always"
